### ISSUE TITLE
Could mapStateToProps be an object?

### ISSUE THREAD

**Issue by selbekk** [reduxjs/react-redux#1048] opened 2018-10-16 07:14 UTC
I'm playing around with selectors, and most of my `mapStateToProps` functions look like this:

```js
const mapStateToProps = state => ({
  isAuthenticated: selectors.isAuthenticated(state),
  isSomethingElse: selectors.isSomethingElse(state),
});
```

Since I always pass on the state, would it be okay to do the same thing as `mapDispatchToProps` does, and just allow sending an object of functions? Like so:

```js
const mapStateToProps = {
  isAuthenticated: selectors.isAuthenticated,
  isSomethingElse: selectors.isSomethingElse,
};
```

Then, `connect` could do the work required to call each of these with the state.

I'd be happy to submit a PR doing this - but what are your thoughts? I'm sure there's a reason the API is the way it is :)

**Comment by timdorr** [comment] 2018-10-16 14:55
It makes the logic around running selectors much more complex. We would have to iterate through all the keys and check for shallow equality there, which could be slow. Also, it becomes more confusing for users. Would this be expected to work?
```js
const mapStateToProps = {
  isAuthenticated: selectors.isAuthenticated,
  foo: {
    isSomethingElse: selectors.isSomethingElse,
  }
}
```
I don't think so, but I could see someone being confused or tripped up by the way they import things. 

It's significantly simpler for us to implement this as just a pure function and also simpler to present to users as an API. So, I don't think we'll add something like this.

**Comment by selbekk** [comment] 2018-10-16 15:06
Fair enough :-)

**Comment by markerikson** [comment] 2018-10-16 18:08
We had a potential PR over at #724 that sat around for a while before we finally closed it.  There's a lot of potential edge cases around the "factory function" syntax that `mapState` supports, and eventually it became more complex than we wanted to deal with.

**Comment by selbekk** [comment] 2018-10-16 18:59
Understandable! Thanks for taking the time to explain! :-)

**Comment by jchook** [comment] 2019-01-19 20:56
I also wondered about this. Seemed lopsided to have `mapDispatchToProps` accept an object, but not `mapStateToProps`.

@selbekk I guess we could use a function like this:

```js
const bindSelectors = (selectors) => (state) => {
  const props = {}
  Object.keys(selectors).forEach(key => {
    props[key] = selectors[key](state)
  })
  return props
}
```

**Comment by markerikson** [comment] 2019-01-22 04:53
I'm willing to potentially reconsider this as long as we keep it narrowly scoped in behavior and implementation.

No factory functions. No nesting.  

I can see two useful forms:

- An array of string key names
- An object of selectors

Both are doable if we keep the behavior limited to basically what @jchook showed.  Question is, whether there's enough benefit for including that functionality.

Tweeted this question: https://twitter.com/acemarke/status/1087568080052596736

I'll reopen this issue for the sake of discussion.

**Comment by manuelbieh** [comment] 2019-01-22 07:49
Would love to see a shorthand notation where I can just pass an object of selectors. It can be so cumbersome to pass state to every single selector over and over again.

**Comment by timdorr** [comment] 2019-01-22 14:49
I really really don't want to do this. Our selector code is complex enough as it is. Just write a `combineSelectors` function and leave it at that. This API is confusing enough as it is.

**Comment by jchook** [comment] 2019-01-22 18:37
Tim, do you think it would be worse than adding `whenMapStateToPropsIsAnObject()`? 

Again, forgive my naive perspective, but I see we have:

### mapDispatchToProps.js
- [`whenMapDispatchToPropsIsFunction()`](https://github.com/reduxjs/react-redux/blob/6e0a1067b8886cef82340aad970da6753ccda119/src/connect/mapDispatchToProps.js#L4)
- [`whenMapDispatchToPropsIsMissing()`](https://github.com/reduxjs/react-redux/blob/6e0a1067b8886cef82340aad970da6753ccda119/src/connect/mapDispatchToProps.js#L10)
- [`whenMapDispatchToPropsIsAnObject()`](https://github.com/reduxjs/react-redux/blob/6e0a1067b8886cef82340aad970da6753ccda119/src/connect/mapDispatchToProps.js#L16)


### mapStateToProps.js
- [`whenMapStateToPropsIsFunction()`](https://github.com/reduxjs/react-redux/blob/6e0a1067b8886cef82340aad970da6753ccda119/src/connect/mapStateToProps.js#L3)
- [`whenMapStateToPropsIsMissing()`](https://github.com/reduxjs/react-redux/blob/6e0a1067b8886cef82340aad970da6753ccda119/src/connect/mapStateToProps.js#L9)
- `whenMapStateToPropsIsAnObject()` ❓


Can we simply add this "missing" factory?

```js
export function whenMapStateToPropsIsObject(mapStateToProps) {
  if (mapStateToProps && typeof mapStateToProps === 'object') {
    return bindSelectors(mapStateToProps)
  }
}
```

**Comment by timdorr** [comment] 2019-01-22 19:17
The issue isn't necessarily hooking it up, it's when it comes to memoizing output and perf issues. That sort of stuff adds a lot more complexity to the code.

**Comment by jchook** [comment] 2019-01-22 19:38
What if we converted it to a function before reaching any of that code?

For example, adding `bindSelectors()` logic [here](https://github.com/reduxjs/react-redux/blob/6e0a1067b8886cef82340aad970da6753ccda119/src/connect/connect.js#L65) before anything else.

Pros:

- Conversion runs once, not on each render
- Converts object to function before the rest of the flow
- Fully supports existing performance enhancements + memoizing

Cons:

- Might break custom factory stuff?
- Could require additional option to turn it off?

To illustrate, consider this workaround that shouldn't cause any render performance impact since it simply preps `mapStateToProps` before giving it to `connect()`:

```js
import { connect as realConnect } from 'react-redux'

export const connect = (Component) => (mapStateToProps, ...args) => (
  realConnect(Component)(
    mapStateToProps && typeof mapStateToProps === 'object'
      ? bindSelectors(mapStateToProps)
      : mapStateToProps,
    ...args
  )
)
```

**Comment by markerikson** [comment] 2019-02-03 04:18
Part of me still kinda wants do to this, but I'll go along with Tim and say it's not worth it to build it in.

**Closed by markerikson** 2019-02-03 04:18 UTC

**Comment by jchook** [comment] 2019-02-05 00:54
Yeah on second look I agree.
