### ISSUE TITLE
Connect not working with detox envinronment

### ISSUE THREAD

**Issue by Daha62** [reduxjs/react-redux#2127] opened 2024-02-06 05:23 UTC
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.2.0
- ReactDOM/React Native: 18.2.0 / 0.72.9
- Redux: 5.0.1
- React Redux: 9.1.0

### What is the current behavior?

While running detox tests in release or debug mode (doesn't matter) react-redux _connect_ function doesn't work. It returns state but it is an initial despite that all requests successfully passed. 
But when we downgrade react-redux package to 8.1.3 all works perfectly.

### What is the expected behavior?

Detox tests on react-redux version 9.1.0 will work as on 8.1.3

### Which browser and OS are affected by this issue?

IOS 16.4

### Did this work in previous versions of React Redux?

- [X] Yes

**Comment by markerikson** [comment] 2024-02-06 06:03
This seems exceptionally surprising, because there is no actual change in how React-Redux v9 works internally from v8. Both rely on React's own `useSyncExternalStore` hook.

In fact, there was literally _no_ change in `connect` whatsoever for v9.

I actually don't know what "Detox" is, and I'm also not an RN user.

At a bare minimum I'd need a full Github repo that demonstrates this happening, with instructions on how to run the tests and reproduce the issue in order to investigate it.  

Beyond that, though, I have a _lot_ of other things on my plate, and a lone bug report of `connect` not working is not something I'm going to have time to look at.  (Not an attempt to brush you off, I'm just being very realistic and up front about how I have to allocate my time right now.)

My only other question atm is: does `useSelector` work in this environment?

**Comment by markerikson** [comment] 2024-05-02 00:45
This seems like it was probably a duplicate of #2150 .

**Closed by markerikson** 2024-05-02 00:45 UTC
