### ISSUE TITLE
mapStateToProps is called when component is not due to render when a dispatch is triggered from componentDidUpdate

### ISSUE THREAD

**Issue by ykagan** [reduxjs/react-redux#1397] opened 2019-09-12 14:10 UTC
When a dispatch is triggered from a lifecycle method as a side-effect of a re-render from a previous dispatch, we wind up calling mapStateToProps on components that are never going to be rendered and are about to be unmounted.

https://github.com/reduxjs/react-redux/pull/1263 fixed a very similar issue when multiple dispatches are triggered simultaneously.

Minimal repro is here: https://codesandbox.io/embed/react-redux-issue-debug-rvr-8whlb

**Comment by ckedar** [comment] 2019-11-08 10:22
The issue is not because of top-down update. This can be verified by overriding the top-down update by providing `store={store}` prop to `App` and `Item` element.

When run with version `5.0.7`, the test case does not throw error, however if we add `console.log` before `invariant` we can see that `mapStateToProps` does throw `invariant` error, just that this error gets swallowed as component does not render subsequently.
 
In `7.1.1`, for some reason, the error caught during `mapStateToProps` is re-thrown during un-mounting, from `unsubscribeWrapper`. This seems to be unnecessary.

**Comment by karolinkas** [comment] 2020-01-15 13:24
I there a workaround for this?

**Comment by lukas1994** [comment] 2020-03-10 23:31
Any updates? Having the same issue.

**Comment by markerikson** [comment] 2021-12-21 03:46
I'm going to close this as a WONTFIX for now, largely because we're encouraging folks to stop using `connect` (even though it'll be fully supported in v8).  This is a real bit of behavior that I can understand is annoying, but I don't think there's a meaningful change we can make at this point, and I don't intend to spend time fixing it myself.

If someone still feels strongly about this please comment, or even better file a PR to improve behavior here.

**Closed by markerikson** 2021-12-21 03:46 UTC

**Comment by lfarroco** [comment] 2022-03-17 19:56
My workaround when encountering this kind of issue is wrapping my dispatches with `batch` to have a single re-render.
`await`ing actions to be fully dispatched can also help
