### ISSUE TITLE
Fix <StrictMode> warnings

### ISSUE THREAD

**Issue by BenoitClaveau** [reduxjs/react-redux#897] opened 2018-03-08 11:33 UTC
Is it possible to replace componentWillReceiveProps because is deprecated to remove React 16+ warning.

**Comment by timdorr** [comment] 2018-03-08 16:08
cWRP isn't deprecated until React 16.4. As of this moment, 16.3 isn't even out. We're looking at larger refactors around async stuff in React 17 in #890.

**Comment by BenoitClaveau** [comment] 2018-03-09 09:30
cWRP seems to be depreacted.

![screenshot_1520587667](https://user-images.githubusercontent.com/5556343/37200316-af5b1a62-2384-11e8-95fd-1e2b442b352f.png)

**Comment by TrySound** [comment] 2018-03-09 09:34
@BenoitClaveau Which version of react do you use? It shouldn't happen until 16.4.

**Comment by respectTheCode** [comment] 2018-03-09 11:35
This started showing up after updating to react-native 0.54.0.

**Comment by respectTheCode** [comment] 2018-03-09 11:41
downgrading to react 16.2.0 doesn't remove the warnings

**Comment by TrySound** [comment] 2018-03-09 12:09
I guess the problem is react-native. AFAIK they published package with react alpha which had this problem. Try to downgrade it.

**Comment by BenoitClaveau** [comment] 2018-03-09 12:57
under "react": "16.2.0",

**Comment by anonrig** [comment] 2018-03-17 17:07
Downgrading shouldn't be the option, since the latest valid version of react-native does deprecated these functions. Is there a ETA on the change?

**Comment by catamphetamine** [comment] 2018-04-02 10:08
`getDerivedStateFromProps` is easy enough using the `compat` thing which isn't a breaking change.
A breaking change is gonna be the `context` replacement which has no `compat` thing so I guess a new major version will be released when React 17 is released.

**Comment by Hypnosphi** [comment] 2018-04-02 12:42
@timdorr I would like to make a PR migrating `react-redux` to new lifecycles using `react-lifecycles-compat` because I don't want `StrictMode` to warn me about my `Connect`ed components. Does it make sense to you?

**Comment by gaearon** [comment] 2018-04-02 12:49
Yes, the purpose of 16.3 was to let libraries start migrating before the deprecation warnings.

**Comment by catamphetamine** [comment] 2018-04-02 12:51
@gaearon I also think it would make a lot of sense for you to include a link to `create-react-context` polyfill same as you did for `react-lifecycles-compat` because otherwise people don't even know that they can transition their libraries to the new context without breaking React 16 users (though breaking all older Reacts).
Specifically I had to google a lot until I accidentally came across that `create-react-context` polyfill thing. It would make life easier for a lot of component mainterners if you included that link as a sidenote in the announcement blog post.

**Comment by timdorr** [comment] 2018-04-02 14:13
Updating the title to better reflect what this is about. I'll put up a failing PR in a sec that others can build off of.

**Comment by timdorr** [comment] 2018-04-02 17:54
OK, phew, got all that done. We're now on React 16, Jest, and react-test-renderer. 

Here's a failing test: #918

**Comment by jamiebuilds** [comment] 2018-04-09 21:36
@Hypnosphi Yeah... create-react-context _only_ polyfills `React.createContext` you are still limited to the rendering features of the versions of React you are compatible with.

**Comment by packetstracer** [comment] 2018-05-10 14:04
has this fix been released? which version?
 I'm using:

`    "react": "^16.3.2",`
`    "react-redux": "^5.0.6",`

and still getting the error in strict-mode.

For example:

` componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: Connect(ProfileHandlerHoc)`

`componentWillUpdate: Please update the following components to use componentDidUpdate instead: Connect(ProfileHandlerHoc)`

**Comment by ritchieanesco** [comment] 2018-05-15 07:10
i've updated to react-redux 5.0.7 and also getting the same warnings as @packetstracer

**Comment by packetstracer** [comment] 2018-05-18 12:57
still throwing these errors after update

```
componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: Connect(DemoSideBarNavContainer), Connect(LanguageSelectorContainer), Connect(ProfileHandlerHoc)

componentWillUpdate: Please update the following components to use componentDidUpdate instead: Connect(DemoSideBarNavContainer), Connect(LanguageSelectorContainer), Connect(ProfileHandlerHoc)
```

package.json content
`    "react-redux": "^5.0.7",`

`cat node_modules/react-redux/package.json `
```
{
  "name": "react-redux",
  "version": "5.0.7",
  "description": "Official React bindings for Redux",
```

Any clue on what could be?

**Comment by slim-hmidi** [comment] 2018-05-31 11:07
So what is the alternative to use until the PR was merged to fix the warnings?

**Comment by Hypnosphi** [comment] 2018-05-31 11:13
@slim-hmidi are you building a library or an app? If the latter, you shouldn't need `StrictMode` for now

**Comment by slim-hmidi** [comment] 2018-05-31 11:16
@Hypnosphi  I'm building an application.

**Comment by daraclare** [comment] 2018-06-15 15:40
Hey folks, any update on the PR being merged? Thanks!

**Comment by grzegorzjudas** [comment] 2018-07-09 13:49
Why was it closed? It's still an issue. Using strict mode or not is developer's decision. Whichever he/she chooses, there's no reason *not to* fix depracation warning. At least this issue should not be closed, as it's **not yet resolved**.

What's the PR, @timdorr?

**Comment by grzegorzjudas** [comment] 2018-07-09 13:53
Anyone coming here with this problem, you can use *react-redux@next* with npm (resolved to 5.1.0-test.1 as of now).

**Comment by timdorr** [comment] 2018-10-10 15:34
Sure. Though either #995 or #1000 is going to solve it.

**Comment by brunolemos** [comment] 2018-11-06 22:11
Now that #1000 was merged, please make sure it works with `StrictMode` as well before releasing! 🙌 cc @timdorr @markerikson

**Comment by brunolemos** [comment] 2018-11-06 23:02
Just tested `6.0.0-beta.2`, it did fix the warnings! :) thanks.

**Comment by timdorr** [comment] 2018-11-07 02:00
Clooooosing out!

**Closed by timdorr** 2018-11-07 02:00 UTC
