### ISSUE TITLE
connect() does not work with React.forwardRef

### ISSUE THREAD

**Issue by malectro** [reduxjs/react-redux#914] opened 2018-03-29 23:44 UTC
Specifically, if I compose `connect` with another HOC that uses `forwardRef`, the result of `forwardRef` (an object) is passed as the `WrappedComponent`, which throws an error claiming it should only be a function.

Example
```js
const MyComponent = React.forwardRef(() => null);
connect()(MyComponent);
```

**Comment by gaearon** [comment] 2018-03-29 23:49
The fix would be to use `require('react-is').isValidElementType()` instead of a strict function check.
See https://github.com/facebook/react/issues/12453.

`react-is` is a new package we just published.

**Comment by gaearon** [comment] 2018-03-29 23:49
(We'd happily take a PR that adds an ESM build to `react-is`. We're using Rollup so it should be easy to expose it.)

**Comment by malectro** [comment] 2018-03-30 01:11
Does passing a forwarded ref type also break `displayName` and `hoistStatics` as well?

**Comment by bvaughn** [comment] 2018-03-30 01:26
> Does passing a forwarded ref type also break displayName and hoistStatics as well?

Yes.

**Comment by gaearon** [comment] 2018-03-30 01:39
We chatted with @sebmarkbage and he pointed out that if you want to "redirect" ref to some *inner* component, `forwardRef` needs to be *outside* of `connect`, not inside it.

```js
class MyComponent extends React.Component {
  render() {
    return <SomeInnerComponent ref={this.props.myForwardedRef} />;
  }
}

const ConnectedMyComponent = connect(
  mapStateToProps
)(MyComponent);

export default forwardRef((props, ref) =>
  <ConnectedMyComponent {...props} myForwardedRef={ref} />
);
```

There is also another scenario in which you might want to point `connect()`ed component's ref to the *wrapped component's own instance* (`MyComponent` in this example). You can't do this in userland. It would need to be done by `connect()` itself because it would need to pass `ref={forwardedRef}` to the wrapped instance (which isn't possible from the user code).

**Comment by malectro** [comment] 2018-03-30 16:44
So it sounds like the solution is to avoid returning forwarded-ref components from HOCs when they're composed and have the user call it as needed?

I'm not totally sure if this example works with the `ref` being in a stateless component.
```jsx
const MyConnectedComponent = _.flow(
  connect(mapStateToProps),
  myHoc(),
)(({myForwardedRef, ...props}) => <MyComponent ref={props.myForwardedRef} {...props} />);

export default forwardRef((props, ref) =>
  <ConnectedMyComponent {...props} myForwardedRef={ref} />
);
```

**Comment by timdorr** [comment] 2018-03-30 17:00
Do we not pass the `ref` prop through? In which case, wouldn't this work?
```js
class MyComponent extends React.Component {
  render() {
    return <SomeInnerComponent ref={this.props.myForwardedRef} />;
  }
}

const ConnectedMyComponent = connect(
  mapStateToProps
)(MyComponent);

export default forwardRef((props, ref) =>
  <ConnectedMyComponent {...props} ref={ref} />
);
```

**Comment by skidding** [comment] 2018-04-23 10:36
> You can't do this in userland. **It would need to be done by connect() itself** because it would need to pass ref={forwardedRef} to the wrapped instance (which isn't possible from the user code).

For a user like me, this sounds ideal. Is this desirable from the your perspective? (Redux core maintainers)

**Comment by gaearon** [comment] 2018-04-23 12:53
It makes sense to me that React Redux should do this. But it would be a breaking change.

**Comment by timdorr** [comment] 2018-04-23 14:06
Again, we already do this. Otherwise, [this test would fail](https://github.com/reactjs/react-redux/blob/master/test/components/connect.spec.js#L294) along with a few others in that file. Am I missing something?

**Comment by gaearon** [comment] 2018-04-23 14:35
Connect is passing all props down. So yes, if the *consumer* uses `forwardRef` it will work.

The proposal is that connect *itself* should use `forwardRef` internally. Then this would work:

```js
class Something extends Component {
  focus() { ... }
}

const Connected = connect(Something)(mapStateToProps)

// Later
<Connected ref={inst => inst && inst.focus()} />
```

**Comment by markerikson** [comment] 2018-04-23 15:16
Seems to me like we're starting to pile up a pretty big list of potential breaking changes here, between this and all the other 16.x-related aspects.  And `React.forwardRef()` is 16.3-only.

**Comment by timdorr** [comment] 2018-04-23 15:17
Sorry, I'm understanding the issue now: The `ref` prop doesn't show up on `this.props` without forwardRef. I wasn't making that connection.

We can definitely look at this with regards to going 16+ only. Is there any sort of polyfill available?

**Comment by skidding** [comment] 2018-04-23 15:49
> The proposal is that connect itself should use forwardRef internally. 

Yes, this is what I was referring to. I'm willing to take a stab at implementing this if you're interested in merging it in. 

With regards to the breaking change: Maybe it can be optional? Not sure where would options for connect go, but I can imagine a minority of users preferring to opt out of this new behavior, even with 16.3+. It should be discouraged going forward, but maybe some code out there depends on reading (private) stuff from the *connect* instance.

**Comment by gaearon** [comment] 2018-04-23 15:55
>The ref prop doesn't show up on this.props without forwardRef. I wasn't making that connection.

It won't show up on `this.props` even with `forwardRef` btw. It is passed as a *second* argument to `forwardRef` callback.

```js
forwardRef((props, ref) => ...)
```

**Comment by gaearon** [comment] 2018-04-23 15:56
>With regards to the breaking change: Maybe it can be optional?

I don't think this makes a lot of sense. There's already a lot of surface area. I think it should be the default behavior (but in the next major).

**Comment by skidding** [comment] 2018-04-23 15:59
> I don't think this makes a lot of sense. There's already a lot of surface area. I think it should be the default behavior (but in the next major).

Fair enough. 

Maybe a silly approach, but can we check if `React.forwardRef` exists and if not fall back to existing behavior? It's still a breaking change, no doubt. But this retains backward compatibility and the next version of react-redux doesn't need to be restricted to React 16.3+.

**Comment by timdorr** [comment] 2018-04-23 16:03
Started a poll to check into this stuff: https://twitter.com/timdorr/status/988448040750067715

Also, found a polyfill, but it looks pretty young: https://github.com/soupaJ/create-react-ref

**Comment by bvaughn** [comment] 2018-04-23 16:15
> Also, found a polyfill, but it looks pretty young: https://github.com/soupaJ/create-react-ref

I would recommend against using this polyfill for this reason:
> ### Caveats
> The polyfilled forwardRef is only compatible with refs created from createRef and not compatible with ref callbacks/functions. If you attach a ref callback to a component returned from the polyfilled forwardRef, you will get a RefForwarder component instance. This is one instance of how this library differs from React's implementation.

The `forwardRef` method would be nice to polyfill, except that it can't be done without introducing a non-standard API. Anyone that used the polyfill would have to deviate from the official API, which would probably cause confusion in the larger community and be more trouble than it's worth.

**Comment by timdorr** [comment] 2018-04-23 16:40
Good news, according to my poll, is 90%+ of folks either are at 16.3 or are able to upgrade to it.

**Comment by markerikson** [comment] 2018-04-23 16:43
Was literally just about to say that :)  Granted, it's a pair of Twitter polls and with only 70-ish results per poll atm, but it's a good indicator.

I personally would say we leave 5.x as the "<= 16.2" line, and focus 6.x as the "compat with 16.3" line.  (And then we're probably looking at 7.x as the "rewrite to something something async React rendering" line.)

**Comment by jedwards1211** [comment] 2018-06-11 22:18
This just burned me when `react-jss` started using `React.forwardRef`: https://github.com/cssinjs/react-jss/issues/255
😢

**Comment by gaearon** [comment] 2018-06-11 22:23
Looks like this is actively impacting users, and https://github.com/reduxjs/react-redux/issues/914#issuecomment-377406014 would be an easy backwards-compatible fix. Am I missing something?

**Comment by gaearon** [comment] 2018-06-11 22:43
>I had no awareness of this forwardRef stuff until my app started catastrophically failing today

Your app broke because you updated a component library (not React!) to a version that includes a breaking change (using `forwardRef`). Note that **React adding `forwardRef`** is not a breaking change; **a component library using `forwardRef`** is.

I don't know whether that component library used a major or a minor release for this, but if you don't want your app to break on random dependency updates and people's mistakes, I encourage you to use a lockfile. Both npm and Yarn provide lockfiles by default. If you like "living on the edge" and having unreproducible builds, it's not surprising your app breaks every now and then.

Again, I want to reiterate there was no breaking change on React's part.

**Comment by jedwards1211** [comment] 2018-06-11 22:49
@gaearon okay, so it was `react-jss`'s mistake then, not releasing it as a breaking change.

**Comment by gaearon** [comment] 2018-06-11 22:51
That is my understanding.

**Comment by jedwards1211** [comment] 2018-06-11 22:53
However I would like to complain that the docs for https://reactjs.org/docs/forwarding-refs.html nowhere state that if a library starts using it, it should be released as a breaking change.

**Comment by gaearon** [comment] 2018-06-11 22:55
I agree, would you like to send a PR? I think at some point I was planning to add it and then it slipped out of my mind. It was a pretty complex release and took weeks of preparation so we missed this.

**Comment by jedwards1211** [comment] 2018-06-11 22:58
@gaearon okay, yes, will do right now

**Comment by jedwards1211** [comment] 2018-06-12 20:30
@gaearon I was just thinking, if `React` provided a `React.isValidComponent` method, then `react-redux` could use that for checking the input component to `connect`.  Has anyone proposed such a function?  I'm sort of surprised it doesn't already exist.

**Comment by cyan33** [comment] 2018-06-23 18:53
What's the current status of this issue now? Does the proposal of using `ReactIs.isValidElementType` to check `WrappedComponent` sounds like the correct way to fix this?

**Comment by jedwards1211** [comment] 2018-06-26 19:37
`isValidElementType` is an awkward naming choice.  My last comment was redundant because I didn't realize it's really checking for a valid component type.  Up until now at least, both React.Component subtypes and functional stateless components are "components".  Was it decided that the return value of `React.forwardRef` isn't properly considered a "component", but it's still an "element type"?  I hate when names get messy like this.

**Comment by cyan33** [comment] 2018-06-26 19:53
@jedwards1211 

It includes all of the possible correct type of React components as per the document:

```js
ReactIs.isValidElementType("div"); // true
ReactIs.isValidElementType(ClassComponent); // true
ReactIs.isValidElementType(StatelessComponent); // true
ReactIs.isValidElementType(ForwardRefComponent); // true
ReactIs.isValidElementType(Context.Provider); // true
ReactIs.isValidElementType(Context.Consumer); // true
ReactIs.isValidElementType(React.createFactory("div")); // true
```

**Comment by gaearon** [comment] 2018-06-26 22:28
I think `isValidComponent` might've been more clearer, but then people would use it like `isValidComponent(<Foo />)` and expect it to return `true` (because they don't know the difference between elements and components).

This is supposed to be a very rarely used API. Most developers don't even know `react-is` exists. So I think verbosity and precision is fine there.

**Comment by pgarciacamou** [comment] 2018-07-12 19:16
@everyone, I added a PR for this, please review.

**Comment by ematipico** [comment] 2018-07-30 15:17
Is this feature inside some roadmap? We are removing `connect` components because they are not able to pass the ref, which is really needed.

**Comment by sibelius** [comment] 2018-08-02 20:13
this is breaking Relay >1.6.1 https://github.com/facebook/relay/issues/2499

is there any workaround for this now?

**Comment by jedwards1211** [comment] 2018-08-04 16:47
@AlicanC Dan Abramov and I made that change to the official documentation recently as a result of issues like this, and the Relay team likely made that release before our documentation changes.

**Comment by jedwards1211** [comment] 2018-08-06 14:04
@alicanc gotcha, yeah, that doesn't sound like a fun situation.

**Comment by sibelius** [comment] 2018-08-06 14:29
The React-Redux fix would be just remove the invariant?

**Comment by jamesreggio** [comment] 2018-08-24 18:13
For those of you just joining —

A fix for this problem (and many other concerns related to React 16.4) is **in progress** in #1000.

Here's to hoping it lands soon. Many thanks to @cellog for taking this on.

**Comment by jamesreggio** [comment] 2018-08-24 18:33
Also, I've published a script that will patch _just the invariant failure_, so that `connect` works on components wrapped by `React.forwardRef`.

https://gist.github.com/jamesreggio/caea042d7a9cd87065a187d5f1f97c62

Read the **Usage** section within the gist, and be sure to note that this patch requires that you install `react-is` as a package dependency.

**Comment by stevemao** [comment] 2018-10-15 22:49
This breaks WithTheme of `styled-components` v4 as they are using `forwardRef`: 

https://github.com/styled-components/styled-components/blob/2b87a5f7e307b16e1b18dc31467d1f04cfe4738a/src/hoc/withTheme.js#L9

**Comment by markerikson** [comment] 2018-10-24 20:50
We were originally planning to address this as part of the larger React-Redux v6 work, as seen in #995 and #1000 .  However, given that this breaks with React 16.6's `React.memo()`, I'm inclined to say we should put out a 5.0.8 / 5.1.0 release that _only_ switches to using `react-is` instead of the current check.

I don't have time to tackle this one myself right now, but if someone can file a PR, @timdorr and I can figure out the release strategy.

**Comment by timdorr** [comment] 2018-10-25 14:13
I'll look into this today at some point.

**Comment by timdorr** [comment] 2018-10-25 14:52
#1062 just landed and closes this out. I'll look at packaging it up for release (namely, if react-is still bloats things a lot). Hopefully today, but I an just a mere mortal.

**Closed by timdorr** 2018-10-25 14:52 UTC

**Comment by timdorr** [comment] 2018-10-25 20:31
5.1.0 is out! https://github.com/reduxjs/react-redux/releases/tag/v5.1.0

**Comment by markerikson** [comment] 2019-02-02 05:47
More specifically, do that only in 6.0+.

**Comment by nelhu** [comment] 2019-03-21 09:06
> 5.1.0 is out! https://github.com/reduxjs/react-redux/releases/tag/v5.1.0

thanks, I spent hours on this issue , you just saved boy

**Comment by ywen** [comment] 2019-04-30 23:52
By setting `{ forwardRef: true }` sets the `ref` to wrapped component. But what we really need is whatever returned by `useImperativeHandle` in the wrapped component. Do I misunderstand anything here? Thanks

**Comment by markerikson** [comment] 2019-05-01 00:17
@ywen : yes, I think you are misunderstanding.  The entire point of `withRef / forwardRef` has been to let you get a reference to the actual instance of your own component that has been wrapped with `connect()`.  You shouldn't be using `forwardRef` to try to access any DOM nodes here.

**Comment by ywen** [comment] 2019-05-01 00:40
> By setting `{ forwardRef: true }` sets the `ref` to wrapped component. But what we really need is whatever returned by `useImperativeHandle` in the wrapped component. The only reason we want to use `forwardRef` is to be able to access the doms in a child component. To return the child component seems to defeat the purpose. Do I misunderstand anything here? Thanks

Never mind, upgrade to `react-redux` 6.0.0 (from 5.1.1) solved the issue. I am deleting the above comment

**Comment by evannorton** [comment] 2020-02-20 20:14
I created a helper function to be used in place of connect that may help people who find this thread. The first parameter is your component (not wrapped with forwardRef). The rest are just `connect`'s parameters.

```import { connect } from "react-redux";
import { forwardRef } from "react";

const connectAndForwardRef (component, mapStateToProps = null, mapDispatchToProps = null, mergeProps = null, options = {}) => connect(mapStateToProps, mapDispatchToProps, mergeProps, {
    ...options,
    forwardRef: true
})(forwardRef(component));```

**Comment by Akiyamka** [comment] 2020-03-23 21:35
I slightly changed the solution proposed by @evannorton  so that it could be drop-in replacement of connect.

```js
import { forwardRef } from 'react';

const connectAndForwardRef = (
  mapStateToProps = null,
  mapDispatchToProps = null,
  mergeProps = null,
  options = {},
) => component => connect(
  mapStateToProps,
  mapDispatchToProps,
  mergeProps,
  {
    ...options,
    forwardRef: true,
  },
)(forwardRef(component));
```

**Comment by amitpatil321** [comment] 2021-01-28 13:33
@JLarky : As JLarky suggested passing extra parameter did the trick

`export default connect(mapStateToProps, mapDispatchToProps, null, {
  forwardRef: true
})(MyContainer);`
