### ISSUE TITLE
useSelector uses equalityFn

### ISSUE THREAD

**Issue by coder-jz** [reduxjs/react-redux#1549] opened 2020-03-17 12:26 UTC
checkForUpdates read equalityFn from the stale closure, so even if equalityFn is changed after the first render, the change doesn't affect

**Comment by dai-shi** [comment] 2020-03-17 13:50
Yeah, I noticed that too some time ago. Not sure if it's intentional, or a bug which is left for a long time.

**Comment by timdorr** [comment] 2020-03-17 14:26
Why would you need to change the equality function on a selector hook after it's instantiated?

**Comment by olejorgenb** [comment] 2020-04-26 19:54
(Duplicate of #1416)

**Closed** 2020-04-27 01:40 UTC
