### ISSUE TITLE
Support Connect a forwardRef Component

### ISSUE THREAD

**Issue by cyan33** [reduxjs/react-redux#964] opened 2018-06-23 06:13 UTC
A simple test case:

```js
it('should not throw an error if a forwardRef is passed to the function returned by connect', () => {
  const ForwardRefComponent = React.forwardRef((props, ref) => null)
  expect(connect()(ForwardRefComponent)).not.toThrow()
})
```

My thoughts on how to fix this:

```
import ReactIs from 'react-is'

function wrapWithConnect(WrappedComponent) {
  invariant(
    typeof WrappedComponent == 'function' || ReactIs.isForwardRef(<WrappedComponent />),
    `You must pass a component to the function returned by ` +
    `${methodName}. Instead received ${JSON.stringify(WrappedComponent)}`
  )
...
```

However, I'm having trouble running the tests in a clean react-redux clone. It could be because of improper configuration or something. Would be much appreciated if someone could help.

**Comment by markerikson** [comment] 2018-06-23 16:00
Appears to be a dupe of #914 .

**Closed by markerikson** 2018-06-23 16:00 UTC
