### ISSUE TITLE
Zombie Children across multiple react roots

### ISSUE THREAD

**Issue by georeith** [reduxjs/react-redux#1556] opened 2020-03-30 10:08 UTC
**What is the current behavior?**

The bug I am experiencing is the same one described here: https://react-redux.js.org/api/hooks#stale-props-and-zombie-children

However this specific cause hasn't been listed and isn't due to using `useSelector`.
My application uses two different React renderers, the official React one and [react-pixi-fiber](https://github.com/michalochman/react-pixi-fiber).

These roots are nested within each other and share a store, there is a `<Provider>` at the top of each root, the store is passed in as a prop to the container of the nested root and then rendered into its `Provider` using `ReactDOM.render()`.

For the most part this works OK and connected components are notified in the correct order, however I am also using [redux-undo](https://github.com/omnidan/redux-undo) and for some reason whenever I dispatch one of its inbuilt actions (`UNDO` or `REDO`) then my connected components in the nested root update before their connected parents have had a chance to rerender, in the case where they would have no longer been rendered (they were deleted) I run into this issue.

**What is the expected behavior?**

Connected components always update after their connected parents have re-rendered.

After reading the article posted about the issue I am of the conclusion this is due to using two separate context providers for the same store (due to having multiple react roots).

I am also unsure as to why the correct order of updates appears to be maintained unless I am dispatching an action to [redux-undo](https://github.com/omnidan/redux-undo).

Short of writing defensive code I was wondering if it is possible to pass enough information from one context to the other so that the existing guards are effective?

**Versions:**

- react: 16.8.3
- react-redux: 7.1.0
- redux: 4.0.1

**Reproduction:** https://codesandbox.io/s/intelligent-silence-32hxl
**To reproduce:**
- Click "Add item"
- Click "Undo" or "Delete"

**Comment by markerikson** [comment] 2020-03-30 14:04
Off the top of my head, I don't expect there's much of anything we can do to maintain consistency across roots in terms of ordering.

Can you put together a CodeSandbox that reproduces the issue?

**Comment by georeith** [comment] 2020-03-30 14:10
@markerikson am attempting to at moment. I'm not sure what about `redux-undo` causes the shift in order considering it's just a higher-order reducer and doesn't to my knowledge trigger side effects. If my reproduction uses that is it still useful?

**Comment by markerikson** [comment] 2020-03-30 14:14
Yes, any repro would be helpful.

**Comment by georeith** [comment] 2020-03-30 15:09
@markerikson I made a minimal reproduction here:

https://codesandbox.io/s/intelligent-silence-32hxl

To reproduce:
- Click "Add item"
- Click "Undo"

Obviously the example I have given is extremely contrived and could be rewritten avoiding that bug entirely but its just designed to trigger the same error in a way that's representative of a more complicated and justified version of it in my app.

**Comment by markerikson** [comment] 2020-03-30 15:14
Hmm.  If I load that sandbox, I'm actually getting an error saying "`store.getState` is not a function".

(and yeah, I do understand that minimal repros may not be fully realistic.)

**Comment by georeith** [comment] 2020-03-30 15:27
@markerikson I think you caught me mid edit as I tried to fix the delete functionality. Should be working now and I won't touch it again 😀

**Comment by markerikson** [comment] 2021-12-21 03:54
I'm going to close this as a WONTFIX for now, largely because we're encouraging folks to stop using `connect` (even though it'll be fully supported in v8).  This is a real bit of behavior that I can understand is annoying, but I don't think there's a meaningful change we can make at this point, and I don't intend to spend time fixing it myself.

If someone still feels strongly about this please comment, or even better file a PR to improve behavior here.

**Closed by markerikson** 2021-12-21 03:54 UTC
