### ISSUE TITLE
Last release v8.0.6 is not installing @reduxjs/toolkit. Version wrong and not found. It is requiring ^5.0.0-beta.0 (redux), but should be ^1.9.5 

### ISSUE THREAD

**Issue by DercilioFontes** [reduxjs/react-redux#2019] opened 2023-05-31 00:30 UTC
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.2.0
- ReactDOM/React Native: 18.2.0
- Redux:
- React Redux: 8.0.6

### What is the current behavior?

Conflict installing.

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-redux@8.0.6
npm WARN Found: @reduxjs/toolkit@1.9.5
npm WARN node_modules/@reduxjs/toolkit
npm WARN   @reduxjs/toolkit@"*" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peerOptional @reduxjs/toolkit@"^5.0.0-beta.0" from react-redux@8.0.6
npm WARN node_modules/react-redux
npm WARN   react-redux@"^8.0.6" from the root project
npm WARN   1 more (@reduxjs/toolkit)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-redux@8.0.6
npm WARN Found: @reduxjs/toolkit@1.9.5
npm WARN node_modules/@reduxjs/toolkit
npm WARN   @reduxjs/toolkit@"*" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peerOptional @reduxjs/toolkit@"^5.0.0-beta.0" from react-redux@8.0.6
npm WARN node_modules/react-redux
npm WARN   react-redux@"^8.0.6" from the root project
npm WARN   1 more (@reduxjs/toolkit)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-redux@8.0.6
npm WARN Found: @reduxjs/toolkit@undefined
npm WARN node_modules/@reduxjs/toolkit
npm WARN   @reduxjs/toolkit@"*" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peerOptional @reduxjs/toolkit@"^5.0.0-beta.0" from react-redux@8.0.6
npm WARN node_modules/react-redux
npm WARN   react-redux@"^8.0.6" from the root project
npm WARN   1 more (@reduxjs/toolkit)
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @reduxjs/toolkit@^5.0.0-beta.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
This PR is setting `"@reduxjs/toolkit": "^5.0.0-beta.0",` line 43
![Screenshot 2023-05-30 at 8 22 30 PM](https://github.com/reduxjs/react-redux/assets/20172847/6ba24ba4-0acd-41bf-be3b-c9c24d79159f)

### What is the expected behavior?

To install fine

### Did this work in previous versions of React Redux?

- [X] Yes

**Comment by EskiMojo14** [comment] 2023-05-31 00:32
thanks for the report! closing as duplicate of #2018 - a fix is in the works :)

**Comment by markerikson** [comment] 2023-05-31 00:32
okay, v8.0.7 is out - please let me know if that fixes the issue!

**Closed by EskiMojo14** 2023-05-31 00:32 UTC
