### ISSUE TITLE
`useSelector` comparator swallows errors

### ISSUE THREAD

**Issue by migueloller** [reduxjs/react-redux#1310] opened 2019-06-11 17:34 UTC
**Do you want to request a _feature_ or report a _bug_?**
Reporting a bug.

**What is the current behavior?**
Errors thrown in `useSelector` comparator are swallowed.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to a CodeSandbox (https://codesandbox.io/s/new) or RN Snack (https://snack.expo.io/) example below:**
https://codesandbox.io/s/redux-useselector-comparator-bug-ho0e4

**What is the expected behavior?**
Error should not be swallowed.

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**
`react@16.8.6`, `react-dom@16.8.6`, `redux@7.1.0`

**Comment by markerikson** [comment] 2019-06-11 18:48
Hmm.  So what I'm seeing here is:

- action is dispatched
    - selector runs
    - comparator runs and throws error
    - error is caught
    - forced re-render
- function component re-renders
    - selector runs synchronously
    - comparator is _not_ called, because we read from the store synchronously and just keep rendering
    - function component renders okay

Conceptually, how would you expect us to handle an error in a comparator?

For that matter, what prompted you to even put together this POC in the first place?  Are you using a seriously custom comparator of some kind that's throwing errors?

**Comment by timdorr** [comment] 2019-06-11 18:50
Ideally, the comparator should be a pure function. Throwing an error is considered a side-effect and is therefore impure. It's similar to throwing an error in a reducer (which is also swallowed).

**Comment by migueloller** [comment] 2019-06-11 19:22
In my case, the comparator was looking at some object fields and an invalid read caused an error. The UI was inconsistent and It took a bit to realize that the comparator was swallowing it.

Maybe logging something in development mode would help? I'm throwing an error in the example, but when I ran into this I assumed my function was pure—it just happened to throw an error.

@timdorr, are errors from reducers being swallowed a `react-redux@7.1.0` thing?

**Comment by timdorr** [comment] 2019-06-11 19:49
That's just a Redux thing: https://github.com/reduxjs/redux/blob/cf749356db98b1dfd8ad089e6899cd5d9eeb0aae/src/createStore.js#L202-L207

**Comment by migueloller** [comment] 2019-06-11 19:55
I just upgraded the CodeSandbox to throw in the reducer and it seems that the error isn't swallowed. Which is interesting considering what you just linked to.

**Comment by timdorr** [comment] 2019-06-12 19:22
That dispatch in useEffect() without any deps is causing an infinite loop. Because of how Codesandbox is built, you don't have access to the error itself, but it's basically being caused by a setState during render.

If you setTimeout the dispatch, you won't get any error: https://codesandbox.io/s/redux-useselector-comparator-bug-p9n27

So, the error is swallowed. There isn't any way to break this behavior without a store enhancer. It's the default for Redux.

**Comment by migueloller** [comment] 2019-06-12 19:31
Nice call. I guess if y'all think it's fine to do what Redux does here it's ok. Is it worth documenting?

**Comment by timdorr** [comment] 2019-06-12 19:40
Sure, we're always open to doc improvements.

**Comment by markerikson** [comment] 2019-06-12 19:41
I'd be okay with logging caught errors in the subscription handler in debug.

**Comment by markerikson** [comment] 2021-12-21 03:35
I _think_ this is likely resolved in v8.  I forked the original sandbox, updated it to React 18 RC and React-Redux v8 beta (and React-Scripts 4), and uncommented the `dispatch()` line.  I immediately saw the standard CRA error overlay:

https://codesandbox.io/s/redux-useselector-comparator-bug-forked-ekp8c?file=/src/index.js

**Closed by markerikson** 2021-12-21 03:35 UTC
