### ISSUE TITLE
'Provider' cannot be used as a JSX component

### ISSUE THREAD

**Issue by JaredDahlke** [reduxjs/react-redux#1886] opened 2022-04-08 22:39 UTC
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 16.13.1
- ReactDOM: 16.13.1
- Redux: 4.0.5
- React Redux: 7.2.1

### What is the current behavior?

get this error when i try to run:
'Provider' cannot be used as a JSX component'

I think it has to do with new @react/types v18

### What is the expected behavior?

no error

### Which browser and OS are affected by this issue?

all

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by markerikson** [comment] 2022-04-08 22:44
@Methuselah96 , @eps1lon : we've been seeing several reports of this.  Is there something else with `@types/react-redux` that needs to be changed to deal with `@types/react@18`?

**Comment by Methuselah96** [comment] 2022-04-08 23:21
Yes, this means that there are conflicting versions of `@types/react` installed (one of them `@types/react@^18` and the other `@types/react@^16 || ^17`). I would recommend trying to combine them in your package lock file or using [package resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) by adding this to your `package.json`:

```
  "resolutions": {
    "@types/react": "^16"
  }
```

(or `^17` if you're on React 17.

**Comment by Methuselah96** [comment] 2022-04-08 23:28
> Is there something else with `@types/react-redux` that needs to be changed to deal with `@types/react@18`?

It works fine with `@types/react@18`, it just doesn't work with multiple versions of `@types/react`. Having multiple versions of `@types/react` has always technically been problematic in theory, but not always in practice because the use of `skipLibCheck` is prolific and the errors tended to not surface in apps.

I'm not sure if there's a way to get React types to work with multiple major versions present. Either way, it's always been advisable to only have a single version of `@types/react` installed.

**Comment by JaredDahlke** [comment] 2022-04-09 00:21
I put this in my package.json to fix it:
`"overrides": {
		"@types/react": "16.9.48"
	}`

you have to have at least version 8 of npm installed to enable `overrides`.

I have quite a few dependencies that are using a wildcard * for their @react/types dependencies which is causing this problem.

also, if you want to, You can force devs to use that version of npm by putting it in the  package.json 
`	"engines": {
		"node": "14.16.1",
		"npm": "8.6.0"
	},`

also had to use npm install --force now which I do not like, but had to get this stop gapped for now. Will be monitoring this and hope to find a better approach such as upgrading or being more specific in my overrides declarations, something like that.

**Comment by eps1lon** [comment] 2022-04-09 07:53
I am [not able to reproduce these issues](https://www.typescriptlang.org/play?jsx=5#code/JYWwDg9gTgLgBAbwApQgN2AEwKZQL5wBmqIcA5FNgIYDGMAtJZgK4AeZAsAFDcA8K6LLjgBnGNGwBeBAgJURcKgDsAnngB8hCBF4B6ARhxR1AbiA). Is somebody able to provide either a [TypeScript playground](https://www.typescriptlang.org/play) or cloneable repository for investigation?

**Comment by eps1lon** [comment] 2022-04-09 08:35
If you're seeing "SomeComponent cannot be used as a JSX component." after installing React 18 types make sure to only have a single version of `@types/react` installed.
Try to dedupe it first by removing it's lockfile entry and running npm/yarn again. 
If you still see duplicate versions of `@types/react` (`yarn why @types/react` or `npm ls @types/react`) try `resolutions` with yarn or [`npm-force-resolutions`](https://www.npmjs.com/package/npm-force-resolutions) with npm.

**Comment by kimbaudi** [comment] 2022-04-09 20:37
I received a similar error yesterday: `'Transition' cannot be used as a JSX component` in a component that uses `react-transition-group` and `@types/react-transition-group` after I updated to `@types/react` v18 and `@types/react-dom` v18.

I first tried to delete the `node_modules` folder and `yarn.lock` file and reinstall, but the error persisted so I used `overrides` in my `package.json` and that got rid of the error.

```json
  "overrides": {
    "@types/react": "17.0.43",
    "@types/react-dom": "17.0.14"
  },
```

Today, I tried again to delete the `node_modules` folder and `yarn.lock` file and reinstall. I also removed the `overrides` in my `package.json`. I'm not sure what happened, but I no longer get the error and I don't have to use `overrides` or `resolutions`.

**Comment by hellatan** [comment] 2022-04-12 03:56
Thanks for mentioning the multiple versions @Methuselah96! It's been awhile since I've had to update react types so I forgot about that little tidbit 🤪 

> I'm not sure if there's a way to get React types to work with multiple major versions present. Either way, it's always been advisable to only have a single version of `@types/react` installed.

We use yarn at my work so I am able to use the `resolutions` field in my `package.json`. After adding 
```json
"resolutions": {
  "@types/react": "^18.0.0"
}
```
to my `package.json` and then running `yarn`, my `yarn.lock` file removed the `@types/react@^17.x.x` dependency, leaving the `@types/react@^18.x.x` version. My issues like `'Provider' cannot be used as a JSX component` and `Type '{}' is not assignable to type 'ReactNode'`, etc were then resolved, which I'm extremely grateful for b/c I really didn't want to have to update anything in DefinitelyTyped 😂 

@kimbaudi I think what you experienced is probably close to what I experienced if you're looking for a possible explanation. Though `overrides` is a `npm` config field and `resolutions` is a `yarn` config field.

**Comment by imt-jaime** [comment] 2022-04-12 10:17
Tried to change "jsx" property from tsconfig.json file to "react" instead of "react-jsx" and it worked.
Maybe de conflict is between TypeScript JSX types and React JSX types, using react types it seems to be solved.
`
{
  "compilerOptions": {
    "jsx": "react"
  }
}
`

**Comment by markerikson** [comment] 2022-04-13 03:10
I'm going to go ahead and close this, but I'll pin the issue for visibility.

**Closed by markerikson** 2022-04-13 03:10 UTC

**Comment by markerikson** [comment] 2022-07-07 19:37
@kukovisuals : per the above discussion, **you need to tell your package manager to force _only_ using `@types/react@18` and `@types/react-dom@18`**.  Your project is currently using v16.9 for the React types, but also React-Redux v8.  

Actually the other issue here is that you're also using React 16 as well.  Technically you can update the `@types/react` and `@types/react-dom` packages to 18 while still using React 16, but it's also a good idea to consider upgrading to React 18 as well.

**Comment by chenEdgar** [comment] 2022-10-26 12:57
> I received a similar error yesterday: `'Transition' cannot be used as a JSX component` in a component that uses `react-transition-group` and `@types/react-transition-group` after I updated to `@types/react` v18 and `@types/react-dom` v18.
> 
> I first tried to delete the `node_modules` folder and `yarn.lock` file and reinstall, but the error persisted so I used `overrides` in my `package.json` and that got rid of the error.
> 
> ```json
>   "overrides": {
>     "@types/react": "17.0.43",
>     "@types/react-dom": "17.0.14"
>   },
> ```
> 
> Today, I tried again to delete the `node_modules` folder and `yarn.lock` file and reinstall. I also removed the `overrides` in my `package.json`. I'm not sure what happened, but I no longer get the error and I don't have to use `overrides` or `resolutions`.

I changed my dependences version and it work now
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/12596622/198031671-818d82dd-a443-4f89-8d77-48dd9e91c82f.png">
