### ISSUE TITLE
Parent component update state but child component state to be out of sync

### ISSUE THREAD

**Issue by linmodev** [reduxjs/react-redux#1158] opened 2019-01-08 11:16 UTC
**What is the current behavior?**

When dispatch an action in parent component the child component does not get newest state.
[reproduce link](https://codesandbox.io/s/29j252z9r)
```ts
import { Component } from "react";
import React from "react";
import { connect, Provider } from "react-redux";
import { createStore } from "redux";
const ReactReduxContext = require("react-redux").ReactReduxContext;

export function bundleComponent(Component: any) {
  return (props: any) => (
    <div {...props}>
      <ReactReduxContext.Consumer>
        {({ store }: { store: any }) => <Sup store={store} />}
      </ReactReduxContext.Consumer>
    </div>
  );
}
class Sub extends Component<any> {
  render() {
    return <div />;
  }
}
const mapStatesToProps = (state: any) => {
  console.log(state, "mapStatesToProps");

  return {};
};
const reduers = (state: {}, action: any) => {
  switch (action.type) {
    case "hitit":
      return Object.assign({}, state, action.state);
    default:
      return state;
  }
};
const store = createStore(reduers, {});

const HocComponent = connect(mapStatesToProps)(Sub);

class Sup extends Component<{ store: any }> {
  componentWillMount() {
    console.log("sup dispatch");
    this.props.store.dispatch({
      type: "hitit",
      state: {
        newfield: 999
      }
    });
  }
  render() {
    return <HocComponent />;
  }
}

export default class AsyncStateFunc extends Component {
  render() {
    let AComponent = bundleComponent(Sup);
    return (
      <Provider store={store}>
        <AComponent />
      </Provider>
    );
  }
}

```
I find this in source code, the variable storeState does not update.If change to store.getState(),I will get expected.

https://github.com/reduxjs/react-redux/blob/e7661b384ae92405cb15360376692acc894d4209/src/components/connectAdvanced.js#L196

**What is the expected behavior?**

Hope state is same all the time.

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**

react 16.7.0
react-redux 6.0

**Comment by timdorr** [comment] 2019-01-08 14:52
Dupe of #1126

**Closed by timdorr** 2019-01-08 14:52 UTC
