### ISSUE TITLE
selector error hiding in connect.js subscribeUpdates 

### ISSUE THREAD

**Issue by jrodriguesimg** [reduxjs/react-redux#1985] opened 2023-01-30 17:41 UTC
When a selector throws an error after the first time it is called, the error is being hidden by redux toolkit.
Example:
```
...
  const value = useSelector((() => {
    let firstTime = true;
    // the actual selector function
    return () => {
      if(firstTime) {
        console.log("first time")
        firstTime = false;
      } else {
        console.log("second time")
        throw "this error will be hidden by redux-toolkit"
      }
      console.log("end")
    }
  })
...
```
The expected console output would be:
```
first time
end
second time
Error: this error will be hidden by redux-toolkit
```
However the last line never shows. It will cause the component where the selector is used to not render as long as it errors.
I found out that the reason for this is that the error is caught and never thrown. I know it should be thrown in `unsubscribeWrapper` but it is not being called on my app.

```
// connect.js
...
    try {
      // Actually run the selector with the most recent store state and wrapper props
      // to determine what the child props should be
      newChildProps = childPropsSelector(latestStoreState, lastWrapperProps.current);
    } catch (e) {
      error = e; // <== where the error is caught and never thrown
      lastThrownError = e;
    }
...
```

It makes it hard to debug errors. Specially when the app has many selectors and because sometimes it is unnoticeable that a bug was introduced. Is there any reason to hide errors here?

**Comment by jrodriguesimg** [comment] 2023-01-30 18:36
You are right I'm going to close this issue and I'll create a new one in react-redux
The issue also happens with connect, but for useSelector the issue is in react-dom.develpment.js

```
function checkIfSnapshotChanged(inst) {
  var latestGetSnapshot = inst.getSnapshot;
  var prevValue = inst.value;

  try {
    var nextValue = latestGetSnapshot();
    return !objectIs(prevValue, nextValue);
  } catch (error) {
    return true;
  }
}
```

**Comment by markerikson** [comment] 2023-01-30 18:37
@jrodriguesimg : I did already move this issue - we're in the React-Redux repo now :)

**Comment by jrodriguesimg** [comment] 2023-01-30 19:05
I used the counter example as a base: [Code Sandbox](https://codesandbox.io/s/festive-flower-es864k?file=/src/TestComponent.js). On this code sand box the components are all unmounted, but on my app they are not being unmounted. What is causing the unmouting of the components in the Code Sandbox?

**Comment by markerikson** [comment] 2023-01-30 19:33
@jrodriguesimg that's why I'm asking for you to show me an example of where this _isn't_ working the way you expect.

**Comment by markerikson** [comment] 2023-01-31 16:05
@jrodriguesimg : **I _really need you to provide an example of the code that you're trying to run_**.  It doesn't have to be a complete app, just a minimal example of "I expected this to fail, and it doesn't", or something along those lines.  But it needs to be _realistic_ (and the way you were defining the selector with the closure for the sandbox earlier isn't realistic).

In general, React will unmount components _if an error is thrown while rendering a component_.  If no error is thrown _while rendering_, then React just keeps rendering normally.

But in order to see what's happening in _your_ app, I need an example that shows me what _your_ code is actually doing so I can understand it.

**Comment by jrodriguesimg** [comment] 2023-01-31 21:32
@markerikson: It is hard for me to give you an example. It is a complex application. The best I can do is to make the exemple more realistic [CodSanbox](https://codesandbox.io/s/busy-panka-np2qjb?file=/src/TestSlice.js). The only way for me to be able to reproduce my issue in code sandbox would be for me to know what is causing the issue.

My issue is that the error is being caught by react-redux, but for some reason my app does not error.
You said:
> And yes, our own useSelector implementation in React-Redux v7, and useSyncExternalStore in React-Redux v8 / React 18, intentionally swallow the error and force a re-render. If it ends up throwing an error during the re-render, you should see that because it will crash the React component tree.

But the re-render does not happen on my app. Can you provide more details of how that re-render is triggered? 

I think in here you are talking about the re-render:
> In general, React will unmount components if an error is thrown while rendering a component.

Probably my app is doing something unexpected, and stopping that re-render from happening.

**Comment by markerikson** [comment] 2023-01-31 22:09
Now I'm really confused.

If I open up that sandbox, the React component tree does indeed crash because the selector is unconditionally throwing an error.

This is exactly the behavior I would expect, and matches what I said above: _if_ an error is thrown _while rendering_, React unmounts the component tree.

So at this point I don't know what you're trying to show me, because it sounds like you're trying to describe a case where the error is throwing and React/React-Redux do _not_ crash.

**Comment by jrodriguesimg** [comment] 2023-02-01 10:27
The sand box does not replicate my issue.
It is hard for me to replicate the issue on a sandbox without knowing how the `useSelector` triggers the re-render after an error.

**Comment by phryneas** [comment] 2023-02-01 10:50
`useSelector` does nothing. It calls `useSyncExternalStore` and that's it. React's `useSyncExternalStore` triggers the rerender.

**Comment by markerikson** [comment] 2023-02-01 14:55
@jrodriguesimg : In general, both `useSelector` and `connect` _should_ catch errors thrown by selectors during dispatch, and force a re-render.

If the error occurs _again_ while rendering, that will force React to crash and unmount the UI.  If the selector succeeds while rendering, then everything's fine.

We've asked several times for examples that actually show us something similar to what you're seeing, so I'm going to close this due to lack of reproduction.

**Closed by markerikson** 2023-02-01 14:55 UTC
